# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'area' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for area

  target 'areaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'areaUITests' do
    # Pods for testing
  end

  platform :ios, '13.0'
#  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
#  pod 'FacebookCore'
#  pod 'FacebookLogin'
#  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

end


#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#    end
#  end
#end
