name: AREA-CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      #- name: build-front
        #run: | 
          #cd front-area && npm install && cd ../
          #npm --prefix front-area run build

      - name: build-api
        run: |
          cd api-area && npm install && cd ../
          npm --prefix api-area run build
# Soon testing commands and CodeCov service
  #deploy:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Deploy on OVH VPS
  #    env:
        #OVH_HOSTING_USER: nero_f
        #OVH_HOSTING_PASSWORD: whispr
        #OVH_HOSTING_DOMAIN: 152.228.134.62
        
        #GCP_HOSTING_USER: nero_f
        #GCP_HOSTING_PASSWORD: whispr
        #GCP_HOSTING_DOMAIN: 34.107.103.52
        #REPOSITORY_NAME: EpitechIT2020/B-YEP-500-BDX-5-1-area-fahad.assoumani
        #REPOSITORY_URL: https://github.com/EpitechIT2020/B-YEP-500-BDX-5-1-area-fahad.assoumani.git
      #run: |
      #  sudo apt-get update
      #  sudo apt-get install sshpass bash openssh-client
      #  sudo sshpass -p "$OVH_HOSTING_PASSWORD" ssh -o StrictHostKeyCHecking=no $OVH_HOSTING_DOMAIN \
      #  'cd source && git pull origin master && cd front-area && npm i --production && npm run build && cp -R build/* /var/www/whispr-area' \
      #  ' && cd ../api-area && npm install && npm run build'
